config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    namespace :admin do
      root to: 'bulletins#index_moderated'
      resources :categories, only: %i[create edit destroy index new show update]
      resources :bulletins, only: [:index] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
    end

    root to: 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/logout', to: 'auth#delete'
    get '/profile', to: 'bulletins#profile'
    resources :bulletins, only: %i[create edit index new show update] do
      member do
        patch :archive
        patch :to_moderate
      end
    end
  end
end

app/views/layouts/web/shared/_flash.html.slim
- if flash.any?
  .container.mb-2
  - flash.each do |type, message|
    div class="container alert #{get_flash_class_for(type)}" role="alert"
      = message

app/views/layouts/web/shared/_nav.html.slim
.d-flex.flex-wrap.align-items-center.py-0.border-bottom
  .navbar.navbar-expand-md.navbar-light.me-auto
    a.navbar-brand.me-md-4[href="/"]
      = t('.home_link')
    #navbarToggler.collapse.navbar-collapse
      ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
        li.nav-item.me-2
          = link_to t('.main'), root_path,
                  class: 'nav-link text-dark'
        - if user_signed_in?
          li.nav-item.me-2
            = link_to t('web.bulletins.profile.my'), profile_path,
                    class: 'nav-link text-dark'
          li.nav-item.me-2
            = link_to t('actions.add'), new_bulletin_path,
                    class: 'nav-link text-dark'

  ul.nav.nav-pills
    - if policy(:admin).permit?
      li.nav-item.me-2
        = link_to t('.administration'), admin_root_path, class: 'nav-link link-dark'
    - if user_signed_in?
      li.nav-item.me-2
        = button_to t('.sign_out'), logout_path,
                method: :delete,
                class: 'nav-link link-dark'

    - else
      li.nav-item.me-2
        = button_to auth_request_path('Github'),
                data: { turbo: false },
                class: 'nav-link link-dark'
          span.bi.bi-github.me-2
          = t('.sign_in')