config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    namespace :admin do
      root to: 'bulletins#index_moderated'
      resources :categories, only: %i[create edit destroy index new show update]
      resources :bulletins, only: [:index] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
    end

    root to: 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/logout', to: 'auth#delete'
    get '/profile', to: 'bulletins#profile'
    resources :bulletins, only: %i[create edit index new show update] do
      member do
        patch :archive
        patch :to_moderate
      end
    end
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :category

  has_one_attached :image, dependent: :purge_later

  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image,
            presence: true,
            file_size: { less_than: 5.megabytes },
            file_content_type: { allow: %w[image/jpg image/jpeg image/png] }

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_id state title]
  end

  aasm :state, column: 'state' do
    state :draft, initial: true
    state :under_moderation
    state :published
    state :rejected
    state :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation rejected published], to: :archived
    end
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class BulletinsController < ApplicationController
      before_action :authorize_admin
      before_action :set_bulletin, only: %i[archive reject publish]

      def index
        @search = Bulletin.ransack(params[:q])
        @bulletins = @search.result.page(params[:page]).per(20)
                            .order(created_at: :desc)
        @back_to_page = admin_bulletins_path
      end

      def index_moderated
        @bulletins = Bulletin.under_moderation.page(params[:page]).per(20)
                             .order(created_at: :desc)
        @back_to_page = admin_root_path
      end

      def archive
        if @bulletin.may_archive?
          @bulletin.archive!
          redirect_to params[:back_to] || admin_root_path, notice: t('.success')
        else
          redirect_to params[:back_to] || admin_root_path, flash: { error: t('.error') }
        end
      end

      def reject
        if @bulletin.may_reject?
          @bulletin.reject!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, flash: { error: t('.error') }
        end
      end

      def publish
        if @bulletin.may_publish?
          @bulletin.publish!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, flash: { error: t('.error') }
        end
      end

      private

      def set_bulletin
        @bulletin = Bulletin.find(params[:id])
      end
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

module Web
  class BulletinsController < ApplicationController
    before_action :set_bulletin, only: %i[archive show edit to_moderate update]
    before_action :authorize_bulletin, only: %i[archive show edit to_moderate update]

    def index
      @search = Bulletin.ransack(params[:q])
      @bulletins = @search.result.published.page(params[:page]).per(20)
                          .order(created_at: :desc)
    end

    def profile
      authorize Bulletin
      @search = current_user.bulletins.ransack(params[:q])
      @bulletins = @search.result.page(params[:page]).per(20)
                          .order(created_at: :desc)
    end

    def to_moderate
      if @bulletin.may_to_moderate?
        @bulletin.to_moderate!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, flash: { error: t('.error') }
      end
    end

    def archive
      if @bulletin.may_archive?
        @bulletin.archive!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, flash: { error: t('.error') }
      end
    end

    def show; end

    def new
      authorize Bulletin
      @bulletin = current_user.bulletins.build
    end

    def edit; end

    def create
      authorize Bulletin
      @bulletin = current_user.bulletins.build(bulletin_params)

      if @bulletin.save
        redirect_to bulletin_url(@bulletin), notice: t('.success')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @bulletin.update(bulletin_params)
        redirect_to bulletin_url(@bulletin), notice: t('.success')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end

    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :category_id, :image)
    end

    def authorize_bulletin
      authorize @bulletin
    end
  end
end

app/views/web/bulletins/_form.html.slim
= simple_form_for(bulletin) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, hint: false
    = f.input :description, hint: false
    = f.association :category, hint: false, collection: Category.order(name: :asc)
    - if bulletin.image_attachment
      = image_tag bulletin.image.variant(resize_to_limit: [200, 100]),
              class: 'img-thumbnail mb-2'
    = f.input :image, as: :file, hint: false
  .form-actions
    = f.button :submit, class: 'mt-4 btn btn-primary'

app/views/web/bulletins/edit.html.slim
.mb-4
  h2
    =< t('.title')
  hr

.row
  == render 'form', bulletin: @bulletin

app/views/web/bulletins/index.html.slim
.mb-4
  h2
    = t('.title')
  hr

.p-3.bg-light
  = search_form_for @search do |f|
    .row.my-2
      .col-5
        = f.input :title_cont, label: false
      .col-4
        = f.input :category_id_eq, as: :select,
                collection: Category.all, label: false
      .col-3
        = f.submit t('search.go'), class: 'btn btn-primary me-2'
        = link_to t('search.reset'), url_for, class: 'btn btn-outline-primary'

.row.mt-2
  - @bulletins.each do |bulletin|
    .col-3.pt-2
      .card.shadow-sm
        - if bulletin.image_attachment
          = image_tag bulletin.image.variant(resize_to_fit: [nil, 200]),
                  height: 200,
                  class: 'card-img-top x-object-fit-cover'
        .card-body
          = link_to bulletin
            h5.card-title
              = bulletin.title
          h6.card-subtitle.mb-2.text-muted
            = distance_of_time_in_words(Time.current, bulletin.created_at)

  = paginate @bulletins

app/views/web/bulletins/new.html.slim
.mb-4
  h2
    =< t('.title')
  hr

.row
  == render 'form', bulletin: @bulletin

app/views/web/bulletins/profile.html.slim
.mb-4
  h2
    = t('.my')
  hr

= link_to t('.new'), new_bulletin_path

.p-3.bg-light.mt-2
  = search_form_for @search, url: profile_path do |f|
    .row.my-2
      .col-5
        = f.input :title_cont, label: false
      .col-4
        = f.input :state_eq, as: :select,
                collection: Bulletin.aasm(:state).states_for_select, label: false
      .col-3
        = f.submit t('search.go'), class: 'btn btn-primary me-2'
        = link_to t('search.reset'), url_for, class: 'btn btn-outline-primary'

.row.mt-2
  table.table.table-borderless
    thead
      tr
        th = t('activerecord.attributes.bulletin.title')
        th = t('activerecord.attributes.bulletin.state')
        th = t('activerecord.attributes.bulletin.created_at')
        th = t('actions.title')

    tbody
      - @bulletins.each do |bulletin|
        tr
          td = bulletin.title
          td = bulletin.aasm(:state).human_state
          td = distance_of_time_in_words(Time.current, bulletin.created_at)
          td
            = link_to t('actions.show'), bulletin_path(bulletin), class: 'me-2'
            = link_to t('actions.edit'), edit_bulletin_path(bulletin), class: 'me-2'
            - if bulletin.may_to_moderate?
              = link_to t('actions.to_moderate'), to_moderate_bulletin_path(bulletin),
                      data: { turbo_method: :patch },
                      class: 'me-2'
            - if bulletin.may_archive?
              = link_to t('actions.archive'), archive_bulletin_path(bulletin),
                      data: { turbo_method: :patch, turbo_confirm: t('actions.archive_confirmation') },
                      class: 'text-danger'

  = paginate @bulletins

app/views/web/bulletins/show.html.slim
.mb-4
  h2
    =< @bulletin.title
  hr
.row
  .col-8
    - if @bulletin.image_attachment
      = image_tag @bulletin.image.variant(resize_to_fit: [400, 300]),
              class: 'img-thumbnail mb-2'
    p
      =< @bulletin.description
  .col-4
    .card
      .card-body
        h1.h5.card-title
          = @bulletin.user.name