config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    namespace :admin do
      root to: 'bulletins#index_moderated'
      resources :categories, only: %i[create edit destroy index new show update]
      resources :bulletins, only: [:index] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
    end

    root to: 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/logout', to: 'auth#delete'
    get '/profile', to: 'bulletins#profile'
    resources :bulletins, only: %i[create edit index new show update] do
      member do
        patch :archive
        patch :to_moderate
      end
    end
  end
end

app/models/bulletin.rb
# frozen_string_literal: true

class Bulletin < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :category

  has_one_attached :image, dependent: :purge_later

  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :image,
            presence: true,
            file_size: { less_than: 5.megabytes },
            file_content_type: { allow: %w[image/jpg image/jpeg image/png] }

  def self.ransackable_attributes(_auth_object = nil)
    %w[category_id state title]
  end

  aasm :state, column: 'state' do
    state :draft, initial: true
    state :under_moderation
    state :published
    state :rejected
    state :archived

    event :to_moderate do
      transitions from: :draft, to: :under_moderation
    end

    event :publish do
      transitions from: :under_moderation, to: :published
    end

    event :reject do
      transitions from: :under_moderation, to: :rejected
    end

    event :archive do
      transitions from: %i[draft under_moderation rejected published], to: :archived
    end
  end
end

app/controllers/web/admin/bulletins_controller.rb
# frozen_string_literal: true

module Web
  module Admin
    class BulletinsController < ApplicationController
      before_action :authorize_admin
      before_action :set_bulletin, only: %i[archive reject publish]

      def index
        @search = Bulletin.ransack(params[:q])
        @bulletins = @search.result.page(params[:page]).per(20)
                            .order(created_at: :desc)
        @back_to_page = admin_bulletins_path
      end

      def index_moderated
        @bulletins = Bulletin.under_moderation.page(params[:page]).per(20)
                             .order(created_at: :desc)
        @back_to_page = admin_root_path
      end

      def archive
        if @bulletin.may_archive?
          @bulletin.archive!
          redirect_to params[:back_to] || admin_root_path, notice: t('.success')
        else
          redirect_to params[:back_to] || admin_root_path, flash: { error: t('.error') }
        end
      end

      def reject
        if @bulletin.may_reject?
          @bulletin.reject!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, flash: { error: t('.error') }
        end
      end

      def publish
        if @bulletin.may_publish?
          @bulletin.publish!
          redirect_to admin_root_path, notice: t('.success')
        else
          redirect_to admin_root_path, flash: { error: t('.error') }
        end
      end

      private

      def set_bulletin
        @bulletin = Bulletin.find(params[:id])
      end
    end
  end
end

app/controllers/web/bulletins_controller.rb
# frozen_string_literal: true

module Web
  class BulletinsController < ApplicationController
    before_action :set_bulletin, only: %i[archive show edit to_moderate update]
    before_action :authorize_bulletin, only: %i[archive show edit to_moderate update]

    def index
      @search = Bulletin.ransack(params[:q])
      @bulletins = @search.result.published.page(params[:page]).per(20)
                          .order(created_at: :desc)
    end

    def profile
      authorize Bulletin
      @search = current_user.bulletins.ransack(params[:q])
      @bulletins = @search.result.page(params[:page]).per(20)
                          .order(created_at: :desc)
    end

    def to_moderate
      if @bulletin.may_to_moderate?
        @bulletin.to_moderate!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, flash: { error: t('.error') }
      end
    end

    def archive
      if @bulletin.may_archive?
        @bulletin.archive!
        redirect_to profile_path, notice: t('.success')
      else
        redirect_to profile_path, flash: { error: t('.error') }
      end
    end

    def show; end

    def new
      authorize Bulletin
      @bulletin = current_user.bulletins.build
    end

    def edit; end

    def create
      authorize Bulletin
      @bulletin = current_user.bulletins.build(bulletin_params)

      if @bulletin.save
        redirect_to bulletin_url(@bulletin), notice: t('.success')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @bulletin.update(bulletin_params)
        redirect_to bulletin_url(@bulletin), notice: t('.success')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end

    def bulletin_params
      params.require(:bulletin).permit(:title, :description, :category_id, :image)
    end

    def authorize_bulletin
      authorize @bulletin
    end
  end
end

app/views/web/admin/bulletins/index.html.slim
h1.h2.mb-4
  = t('web.bulletins.index.title')

.row.mt-2
  .p-3.bg-light
    = search_form_for @search, url: admin_bulletins_path do |f|
      .row.my-2
        .col-5
          = f.input :title_cont, label: false
        .col-4
          = f.input :state_eq, as: :select,
                  collection: Bulletin.aasm(:state).states_for_select, label: false
        .col-3
          = f.submit t('search.go'), class: 'btn btn-primary me-2'
          = link_to t('search.reset'), url_for, class: 'btn btn-outline-primary'

  table.table.table-borderless
    thead
      tr
        th = t('activerecord.attributes.bulletin.title')
        th = t('activerecord.attributes.bulletin.state')
        th = t('activerecord.attributes.bulletin.created_at')
        th = t('actions.title')

    tbody
      - @bulletins.each do |bulletin|
        tr
          td = link_to bulletin_path(bulletin)
            = bulletin.title
          td = bulletin.aasm(:state).human_state
          td = distance_of_time_in_words(Time.current, bulletin.created_at)
          td
            = link_to t('actions.show'), bulletin_path(bulletin), class: 'me-2'
            - if bulletin.may_archive?
              = link_to t('actions.archive'), archive_admin_bulletin_path(bulletin, back_to: @back_to_page),
                      data: { turbo_method: :patch, turbo_confirm: t('actions.archive_confirmation') },
                      class: 'text-danger'

  = paginate @bulletins

app/views/web/admin/bulletins/index_moderated.html.slim
h1.h2.mb-4
  = t('web.bulletins.moderation.title')

.row.mt-2
  table.table.table-borderless
    thead
      tr
        th = t('activerecord.attributes.bulletin.title')
        th = t('activerecord.attributes.bulletin.created_at')
        th = t('actions.title')

    tbody
      - @bulletins.each do |bulletin|
        tr
          td = bulletin.title
          td = distance_of_time_in_words(Time.current, bulletin.created_at)
          td
            = link_to t('actions.publish'), publish_admin_bulletin_path(bulletin),
                    data: { turbo_method: :patch },
                    class: 'me-2'
            = link_to t('actions.reject'), reject_admin_bulletin_path(bulletin),
                    data: { turbo_method: :patch },
                    class: 'me-2'
            = link_to t('actions.archive'), archive_admin_bulletin_path(bulletin, back_to: @back_to_page),
                    data: { turbo_method: :patch, turbo_confirm: t('actions.archive_confirmation') },
                    class: 'text-danger'

  = paginate @bulletins