config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    namespace :admin do
      root to: 'bulletins#index_moderated'
      resources :categories, only: %i[create edit destroy index new show update]
      resources :bulletins, only: [:index] do
        member do
          patch :archive
          patch :publish
          patch :reject
        end
      end
    end

    root to: 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/logout', to: 'auth#delete'
    get '/profile', to: 'bulletins#profile'
    resources :bulletins, only: %i[create edit index new show update] do
      member do
        patch :archive
        patch :to_moderate
      end
    end
  end
end

app/views/layouts/web/admin/application.html.slim
doctype html
html.h-100
  head
    title = t('layouts.web.shared.nav.administration')
    == csrf_meta_tags
    == csp_meta_tag
    meta name="keywords" content="template language"
    meta name="author" content='author'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_importmap_tags
    = javascript_include_tag 'application', 'data-turbo-track': 'reload',
            defer: true

  body.d-flex.flex-column.h-100
    .container.mb-2.mt-2
      = render 'layouts/web/shared/nav'

    = render 'layouts/web/shared/flash'

    main.container
      .row
        .col-md-3
          ul.nav.flex-column.nav-pills
            li.nav-item
              = link_to t('.under_moderation'), admin_root_path,
                      class: "nav-link  link-dark #{active_moderation}"
            li.nav-item
              = link_to t('.all_bulletins'), admin_bulletins_path,
                      class: "nav-link  link-dark #{active_bulletins}"
            li.nav-item
              = link_to t('.categories'), admin_categories_path,
                      class: "nav-link  link-dark #{active_categories}"
        .col-md-9
          == yield

    footer.mt-auto
      .container-xl
        .row.py-2
          = t('layouts.hexlet_title', year: Time.current.year)